### ISSUE TITLE
Add Versioning Information

### ISSUE THREAD

**Issue by wsdmatty** [tsmetana/spotify-tray#1]
No versioning information associated with project.
I propose the following tags.
git tag v0.0.1 db78e1b ---Lightweight tag, Initial 'working' version.
git tag -a v1.0.0 0f6912f --- First stable release. (You took a break of a few months after this, so I assume it was stable)
git tag -a v1.1.0 2793099 --- Latest release version. Again, some time since the commit so I assume it's stable.

**Comment by tsmetana** [comment]
OK. First release is out.
