### ISSUE TITLE
minimize to tray will not working

### ISSUE THREAD

**Issue by NicoleCollard** [tsmetana/spotify-tray#11]
After install the lates spotify-tray release (1.2.1 RPM) and startup spotify with the spotify-tray starts with success but to minimize the spotify window will not automatically to tray, only by clicking on the spotify icon in the tray it will be toggle.

**Comment by tsmetana** [comment]
This is how it is supposed to work. ;) If you minimize the window, it will get minimized the same way as it normally would -- I expect the users who click the minimize window button really want the window not to be hidden completely (i.e. stay visible in a taskbar or similar). Thinking about it... I can let the window to unminimize when the user left-click the tray icon if it's minimized. That sounds intuitive and I think it might be doable... I'll try it out.

**Comment by NicoleCollard** [comment]
Sorry then i definitely misunderstood the function, everything seems to work correctly. ;)

**Comment by tsmetana** [comment]
Improved with 3b7d85c.
