### ISSUE TITLE
Feature request: Previous/next track on scrolling during hover

### ISSUE THREAD

**Issue by AnySomebody1** [tsmetana/spotify-tray#12]
Thanks for your work! I guess the title is fairly self explaining. I like it that I can change my volume level in XFCE via scroll wheel. I would also like it if I could change current track by scrolling on the spotify icon.

**Comment by tsmetana** [comment]
Sounds simple and useful. Will take a look on the weekend. Thanks for the suggestion.

**Comment by AnySomebody1** [comment]
Thanks! :)
When you already on it anyway you might also want to consider adding Play/Pause command on middle click :)

**Comment by allanlaal** [comment]
I vote for #13 instead of #12

**Comment by tsmetana** [comment]
I already have the volume plugin in the tray that can change the volume on mouse scroll and I assume it's pretty standard (see the first comment). So I found the feature requested in this issue to be more useful. Also, it's been implemented in the commit 3d9f5b6.
