### ISSUE TITLE
ADD Middle Click = Next 

### ISSUE THREAD

**Issue by allanlaal** [tsmetana/spotify-tray#13]
this is a common behaviour in other audio player tray icons in Linux :)

**Comment by allanlaal** [comment]
I vote for #13 instead of #12

**Comment by tsmetana** [comment]
I like the #12 more actually. I know that e.g. audacious behaves this way and I dislike it -- I don't need several ways to change volume and middle click is clumsier than mouse wheel scroll. Thanks for the suggestions though.

**Comment by allanlaal** [comment]
please reopen :)

**Comment by allanlaal** [comment]
please add mouse actions to SNI Notification area (newer standard) aswell, the mouse buttons seem to do nothing in the old style Notification Area

https://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/
