### ISSUE TITLE
ADD Mouse main scroll = Volume Up/Down

### ISSUE THREAD

**Issue by allanlaal** [tsmetana/spotify-tray#14]
this is a common behaviour in other audio player tray icons in Linux :)

**Comment by tsmetana** [comment]
The volume plugins can already do this... See the issue #12.

**Comment by allanlaal** [comment]
## use case

 I have a system for always having background music ready in a nanosecond:

### Audacious

24/7 playing my favourite internet radio


### Rhythmbox

24/7 playing music from my hdd

### Spotify

playing a specific mood


I have 1 of them playing and the others muted, so a simple mousescroll on the icon will play music from that source
volume scroll is faster than waiting the player to start playing sth (or SpaghettiMonster forbid, opening up that players UI to press Play :vomiting_face: )

**Comment by allanlaal** [comment]
please add mouse actions to SNI Notification area (newer standard) aswell, the mouse buttons seem to do nothing in the old style Notification Area

https://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/

**Comment by allanlaal** [comment]
linked to #13

**Comment by allanlaal** [comment]
please reopen ! :)
