### ISSUE TITLE
Tray Icon low quality

### ISSUE THREAD

**Issue by MarioDena** [tsmetana/spotify-tray#16]
For now the tray work perfectly, however the tray icon looks like a 16px resolution image.
Is there a way to use the spotify icon from our theme insted? Or at least have a higher resolution icon?

**Comment by drizzt** [comment]
And with KDE the icon is garbaged

**Comment by tsmetana** [comment]
There are no icons shipped with spotify-tray: I take them from the system in this order:`spotify-indicator`
		"spotify",
		"spotify-client",

**Comment by MarioDena** [comment]
> There are no icons shipped with spotify-tray: I take the first one from the system, searching in this order: `spotify-indicator`, `spotify`, `spotify-client`. So the icon used is whatever the theme or distribution offers under these names. Also there is nothing special about the icon rendering (not sure what "garbaged" means in this context), the program just uses GTK for the icon displaying.

There are several versions of the Icon and your add-on will display a horrible Icon on large resolutions, I get it f you think this is not important but then how about adding an option for the user to set the Icon?

**Comment by tsmetana** [comment]
> There are several versions of the Icon and your add-on will display a horrible Icon on large resolutions, I get it f you think this is not important but then how about adding an option for the user to set the Icon?

All right. Let's add another command line option.

**Comment by ottersarecool** [comment]
I have the same "issue" the tray icon is very low quality for some reason on KDE

**Comment by tsmetana** [comment]
Should have been fixed by the commit e878dbd.

**Comment by illiakozey** [comment]
is it matter what type of image icon will be?

**Comment by tsmetana** [comment]
> does it matter what extension will an icon have?
No, the extension (i.e., the filename) as such doesn't matter. But the image format does. It has to be supported by GDK. The usual ones (png, jpg, svg,...) work.
