### ISSUE TITLE
Using w/ Spotify adblock?

### ISSUE THREAD

**Issue by wazlecracker** [tsmetana/spotify-tray#17]
Hello! How would one go about using this with [Spotify Adblock](https://github.com/abba23/spotify-adblock)? I've tried running it as `LD_PRELOAD=/usr/lib/spotify-adblock.so spotify-tray` but that returns the error `spotify-tray: symbol lookup error: /usr/lib/spotify-adblock.so: undefined symbol: cef_string_userfree_utf16_free`.

**Comment by tsmetana** [comment]
The `cef_string_userfree_utf16_free` comes from Chromium or some of its libraries AFAIK. Looks like the Spotify Adblock is wrapping lots of those but probably not exporting this symbol correctly (?). The spotify-tray binary doesn't depend on anything from Chrome, so this is hardly caused by it.

**Comment by wazlecracker** [comment]
This isn't a bug report. I'm trying to figure out how to use your tool in conjunction with Spotify Adblock.

**Comment by bennyhillthebest** [comment]
I would like to know also if there is a way to use both abba23's spotify-adblock and spotify-tray together, thanks

**Comment by wazlecracker** [comment]
I did a work-around by creating an executable file with 

```bash
#!/bin/bash
LD_PRELOAD=/usr/lib/spotify-adblock.so spotify & sleep 1 && spotify-tray -m
```
as the contents, then created a `.desktop` file with the `Exec=` line pointing to the file. Sending the window to the tray or bringing it to the front requires clicking the tray icon itself, but it works.

**Comment by MrCuriousCat** [comment]
```
#!/bin/bash

LD_PRELOAD=/usr/lib/spotify-adblock.so spotify & sleep 1

while [ ! $(xwininfo -name "spotify") ]
do
	echo "waiting for spotify"
	sleep 5
done

sleep 5

spotify-tray
echo "done"
```
did some modification on @wazlecracker's code to prevent the script from launching 2 instances of spotify when spotify is slower than the sleep timer that it launches spotify-tray first

**Comment by night-every** [comment]
`#!/bin/sh

export LD_LIBRARY_PATH="/usr/lib64/apulse"

if command -v spotify-dbus.py > /dev/null; then
	echo "Launching spotify with Gnome systray integration."
	spotify-dbus.py "$@"
elif command -v spotify-tray > /dev/null; then
	echo "Launching spotify with generic systray integration."
	minimized=
	for arg; do
		if [ "$arg" = --minimized ]; then
			minimized=$arg
			break
		fi
	done
	LD_LIBRARY_PATH=/opt/spotify/spotify-client LD_PRELOAD=/usr/lib64/spotify-adblock.so /opt/spotify/spotify-client/spotify & sleep 1
	while [ ! $(xwininfo -name "spotify") ]
	do
        	echo "waiting for spotify"
        	sleep 5
	done

	sleep 5

	spotify-tray --toggle $minimized -- "$@"

	#spotify-tray \
	#	--client-path="/opt/spotify/spotify-client/spotify" --toggle $minimized -- "$@"
else
	echo "Neither gnome-integration-spotify nor spotify-tray are installed."
	echo "Launching spotify without systray integration."
	#exec "LD_LIBRARY_PATH=/opt/spotify/spotify-client LD_PRELOAD=/usr/lib64/spotify-adblock.so /opt/spotify/spotify-client/spotify" "$@"
	LD_LIBRARY_PATH=/opt/spotify/spotify-client LD_PRELOAD=/usr/lib64/spotify-adblock.so /opt/spotify/spotify-client/spotify

fi


`

GENTOO VERSION , replace it with /usr/bin/spotify

**Comment by night-every** [comment]
```
#!/bin/sh

export LD_LIBRARY_PATH="/usr/lib64/apulse"

if command -v spotify-dbus.py > /dev/null; then
	echo "Launching spotify with Gnome systray integration."
	spotify-dbus.py "$@"
elif command -v spotify-tray > /dev/null; then
	echo "Launching spotify with generic systray integration."
	minimized=
	for arg; do
		if [ "$arg" = --minimized ]; then
			minimized=$arg
			break
		fi
	done
	LD_LIBRARY_PATH=/opt/spotify/spotify-client LD_PRELOAD=/usr/lib64/spotify-adblock.so /opt/spotify/spotify-client/spotify & sleep 1
	while [ ! $(xwininfo -name "spotify") ]
	do
        	echo "waiting for spotify"
        	sleep 5
	done

	sleep 5

	spotify-tray --toggle $minimized -- "$@"

	#spotify-tray \
	#	--client-path="/opt/spotify/spotify-client/spotify" --toggle $minimized -- "$@"
else
	echo "Neither gnome-integration-spotify nor spotify-tray are installed."
	echo "Launching spotify without systray integration."
	#exec "LD_LIBRARY_PATH=/opt/spotify/spotify-client LD_PRELOAD=/usr/lib64/spotify-adblock.so /opt/spotify/spotify-client/spotify" "$@"
	LD_LIBRARY_PATH=/opt/spotify/spotify-client LD_PRELOAD=/usr/lib64/spotify-adblock.so /opt/spotify/spotify-client/spotify

fi


```

GENTOO VERSION , Replace /usr/bin/spotify with this

**Comment by night-every** [comment]
> ```
> #!/bin/bash
> 
> LD_PRELOAD=/usr/lib/spotify-adblock.so spotify & sleep 1
> 
> while [ ! $(xwininfo -name "spotify") ]
> do
> 	echo "waiting for spotify"
> 	sleep 5
> done
> 
> sleep 5
> 
> spotify-tray
> echo "done"
> ```
> 
> did some modification on @wazlecracker's code to prevent the script from launching 2 instances of spotify when spotify is slower than the sleep timer that it launches spotify-tray first

THANKS
