### ISSUE TITLE
Tray Menu: Like Current Song / Toggle Liked?

### ISSUE THREAD

**Issue by chainria** [tsmetana/spotify-tray#18]
Thank you very much for this great little wrapper. I am using it quite fondly.

However I found myself often missing the option to like a track that is currently playing. It is the only time I need to restore the window right now. So I was wondering if it would be possible to implement this feature? Unfortunately I don't know if this is possible at all however.

**Comment by tsmetana** [comment]
I'm afraid this is not really possible. The only API the Spotify client app offers is the [D-Bus MPRIS](https://specifications.freedesktop.org/mpris-spec/latest/) interface (and we can be glad at least for that), but that doesn't in any way offer a method to read or manipulate the track "like". Really sorry, but I think I can't help you. I agree it would be an useful feature.

**Comment by chainria** [comment]
Thank you for your very quick response. Already was fearing something like this, back in the days I was among all those voices pleading for MPRIS support in the forums. So yeah, let's just be glad that they included that one at least.
