### ISSUE TITLE
Programmatic way to show the spotify window

### ISSUE THREAD

**Issue by AdamSLevy** [tsmetana/spotify-tray#2]
I need spotify to be launched with certain flags that are set in its desktop entry. So I launch spotify using `dex` which can launch desktop entries from the cli.

If I open spotify-tray too soon after, then I get multiple instances of spotify. I tried a number of approaches but settled on this bash script as my launcher for both. I'm using i3 so it uses i3-msg to focus the already open spotify window. 

```
#!/bin/bash

if pgrep -f /usr/bin/spotify || pgrep -f /opt/spotify/spotify || pgrep -f /usr/bin/spotify-tray; then
        i3-msg '[class="Spotify"] focus'
        exit 0
fi

i3-msg 'exec dex /usr/share/applications/spotify.desktop'

# Let spotify start so that the tray doesn't restart it.
sleep .5
i3-msg 'exec --no-startup-id dex /usr/share/applications/spotify-tray.desktop'
```

This works well to prevent multiple instances of spotify or spotify-tray from being launched. However if spotify is currently hidden, then i3 cannot target the window for focus. It could if there was a way to send a signal to spotify-tray to show the window.

**Comment by AdamSLevy** [comment]
Additionally, it'd be nice if spotify-tray would perform better checks that neither spotify nor spotify-tray is not already running so I wouldn't have to work so hard to prevent it in my script.

**Comment by tsmetana** [comment]
I think I can let spotify-tray to listen on D-Bus and export a method to show the Spotify client window. Then I should be able to detect a running instance and just send it a message instead of launching "completely" if started for the second time.

As for detecting a running Spotify client: I attempted to do so already -- spotify-tray should launch a new client only when no Spotify window is found. This requires EWMH compliant window manager (_NET_CLIENT_LIST property must be properly set) and the window has WM_CLASS set to "spotify" though.

**Comment by AdamSLevy** [comment]
Does spotify-tray check if spotify-tray is already running? I am able to launch two instances of spotify-tray right now, so it seems like its not.

Also if spotify-tray is detecting a running instance of spotify solely by the presence of a window, and it doesn't check if the tray is already running, then it might launch another instance of spotify, and be running redundantly as well.

Finally, the way in which spotify is being launched doesn't take into account any additional flags added in a desktop entry. That's why I am launching spotify using `dex`. I need to be able to pass settings to spotify like `--force-device-scale-factor=2` for correct scaling on my hidpi system.

I believe it's detecting my spotify window just fine in i3. It can just be race-y and easy to launch two instances of the tray and spotify. Here is the output from `xprop`
```
_NET_WM_ICON(CARDINAL) = 
WM_CLASS(STRING) = "spotify", "Spotify"
WM_NAME(STRING) = "Spotify Premium"
_NET_WM_NAME(UTF8_STRING) = "Spotify Premium"
_NET_WM_DESKTOP(CARDINAL) = 0
_NET_WM_STATE(ATOM) = 
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
XdndProxy(WINDOW): window id # 0x5a00002
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 0, 0
		window gravity: Static
_NET_WM_PID(CARDINAL) = 690505
WM_LOCALE_NAME(STRING) = "en_US.UTF-8"
WM_CLIENT_MACHINE(STRING) = "<hostname>"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, _NET_WM_PING
```

**Comment by AdamSLevy** [comment]
I made some edits to the above comment.

**Comment by tsmetana** [comment]
If you're able to test the git clone, the commit 10a8bbf2f0a9a53b4414021fa8f18d60e00543e0 should fix the issue.

**Comment by tsmetana** [comment]
... and I probably should allow to pass options to the spotify application itself.

**Comment by AdamSLevy** [comment]
Awesome! The spotify window is now shown when spotify-tray is called after its already running.

And yes, being able to pass additional options for starting spotify would be awesome!

**Comment by AdamSLevy** [comment]
Also adding a way to hide the window programmatically would probably make people who like to customize shortcut keys like i3wm users pretty happy. 

But just being able to show and focus spotify with a keyboard key alone makes me pretty happy. Thank you so much!

**Comment by tsmetana** [comment]
OK. There's also a HideWindow method there now, so you can use something like dbus-send to control the window visibility from the command line.

**Comment by tsmetana** [comment]
I'll take a look at passing the arguments later. I think this issue has been resolved now.

**Comment by R-L-T-Y** [comment]
Dbus way does work! Maybe a toggle method can be implemented. Or better, passing the arguments, like `spotify-tray toggle` so that it can be easier for WM to handle hotkey binding.

**Comment by tsmetana** [comment]
> Dbus way does work! Maybe a toggle method can be implemented. Or better, passing the arguments, like `spotify-tray toggle` so that it can be easier for WM to handle hotkey binding.

Hm... Implementing the D-Bus method is trivial. Thinking about it I actually like even the idea of the "toggle" argument.

**Comment by tsmetana** [comment]
The new version should be more comfortable to use now.
