### ISSUE TITLE
Issue with Gtk 3.0

### ISSUE THREAD

**Issue by TheLumbee** [tsmetana/spotify-tray#20]
Getting this error:

```
checking for GTK... no
configure: error: Package requirements (gtk+-3.0) were not met:

No package 'gtk+-3.0' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables GTK_CFLAGS
and GTK_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

Running Ubuntu 20.04. Not sure what dependencies need to be installed.

**Comment by kelebek333** [comment]
You can install my PPA.

```
sudo add-apt-repository ppa:kelebek333/tools
sudo apt-get update
sudo apt install spotify-tray
```

Or You can install with that packages without adding PPA. http://ppa.launchpad.net/kelebek333/tools/ubuntu/pool/main/s/spotify-tray/

**Comment by kelebek333** [comment]
You can install from PPA with following commands.

```
sudo add-apt-repository ppa:kelebek333/tools
sudo apt-get update
sudo apt install spotify-tray
```

Or You can install with that packages without adding PPA. http://ppa.launchpad.net/kelebek333/tools/ubuntu/pool/main/s/spotify-tray/

**Comment by tsmetana** [comment]
I didn't know about @kelebek333's PPA. It might be the simplest way to get the binaries for Ubuntu. However if you still wish to compile the source yourself: You seem to be missing the gtk+-3 development package, so most likely `apt-get install libgtk-3-dev` would solve the problem.

**Comment by allanlaal** [comment]
using master tip 989e9a1204e52a9845c350069a88f5e62ae3d9b8 :


	  root@L4:/home/allan# aptitude install libgtk-3-dev
	  libgtk-3-dev is already installed at the requested version (3.24.33-1ubuntu1)

but configure still fails with:

	  allan@L4:/opt/spotify-tray$ ./autogen.sh
	  autoreconf: export WARNINGS=
	  autoreconf: Entering directory '.'
	  autoreconf: configure.ac: not using Gettext
	  autoreconf: running: aclocal --force 
	  autoreconf: configure.ac: tracing
	  autoreconf: configure.ac: not using Libtool
	  autoreconf: configure.ac: not using Intltool
	  autoreconf: configure.ac: not using Gtkdoc
	  autoreconf: running: /usr/bin/autoconf --force
	  configure.ac:6: warning: The macro `AC_GNU_SOURCE' is obsolete.
	  configure.ac:6: You should run autoupdate.
	  ./lib/autoconf/specific.m4:312: AC_GNU_SOURCE is expanded from...
	  configure.ac:6: the top level
	  configure.ac:10: warning: The macro `AC_HEADER_STDC' is obsolete.
	  configure.ac:10: You should run autoupdate.
	  ./lib/autoconf/headers.m4:704: AC_HEADER_STDC is expanded from...
	  configure.ac:10: the top level
	  configure.ac:19: warning: AC_OUTPUT should be used without arguments.
	  configure.ac:19: You should run autoupdate.
	  autoreconf: running: /usr/bin/autoheader --force
	  autoreconf: running: automake --add-missing --copy --force-missing
	  autoreconf: Leaving directory '.'
	  allan@L4:/opt/spotify-tray$ ./configure
	  checking for a BSD-compatible install... /usr/bin/install -c
	  checking whether build environment is sane... yes
	  checking for a race-free mkdir -p... /usr/bin/mkdir -p
	  checking for gawk... gawk
	  checking whether make sets $(MAKE)... yes
	  checking whether make supports nested variables... yes
	  checking whether make supports the include directive... yes (GNU style)
	  checking for gcc... gcc
	  checking whether the C compiler works... yes
	  checking for C compiler default output file name... a.out
	  checking for suffix of executables... 
	  checking whether we are cross compiling... no
	  checking for suffix of object files... o
	  checking whether the compiler supports GNU C... yes
	  checking whether gcc accepts -g... yes
	  checking for gcc option to enable C11 features... none needed
	  checking whether gcc understands -c and -o together... yes
	  checking dependency style of gcc... gcc3
	  checking for stdio.h... yes
	  checking for stdlib.h... yes
	  checking for string.h... yes
	  checking for inttypes.h... yes
	  checking for stdint.h... yes
	  checking for strings.h... yes
	  checking for sys/stat.h... yes
	  checking for sys/types.h... yes
	  checking for unistd.h... yes
	  checking for wchar.h... yes
	  checking for minix/config.h... no
	  checking whether it is safe to define __EXTENSIONS__... yes
	  checking whether _XOPEN_SOURCE should be defined... no
	  checking for gcc... (cached) gcc
	  checking whether the compiler supports GNU C... (cached) yes
	  checking whether gcc accepts -g... (cached) yes
	  checking for gcc option to enable C11 features... (cached) none needed
	  checking whether gcc understands -c and -o together... (cached) yes
	  checking dependency style of gcc... (cached) gcc3
	  checking for grep that handles long lines and -e... /usr/bin/grep
	  checking for egrep... /usr/bin/grep -E
	  ./configure: line 5462: libgdk3.0-cil-dev: command not found
	  checking for pkg-config... /home/linuxbrew/.linuxbrew/bin/pkg-config
	  checking pkg-config is at least version 0.9.0... yes
	  checking for gtk+-3.0... no
	  configure: error: Package requirements (gtk+-3.0) were not met:
	  
	  No package 'gtk+-3.0' found
	  
	  Consider adjusting the PKG_CONFIG_PATH environment variable if you
	  installed software in a non-standard prefix.
	  
	  Alternatively, you may set the environment variables GTK_CFLAGS
	  and GTK_LIBS to avoid the need to call pkg-config.
	  See the pkg-config man page for more details.
	  allan@L4:/opt/spotify-tray$

**Comment by allanlaal** [comment]
sorry for that, fixed by https://github.com/Homebrew/brew/issues/13281#issuecomment-1127672796
