### ISSUE TITLE
Can't work for snap package spotify

### ISSUE THREAD

**Issue by livrth** [tsmetana/spotify-tray#21]
System:Ubuntu20.04 LTS

First I manually install by steps in README, but still no icons in top bar, even if I restart the spotify or gnome shell.
Then I see the ppa repo in #20 , after doing ```sudo apt install spotify-tray```, it shows ```Depends: spotify-client but it is not installable```, so it means only install spotify from apt repo can work.

So is there a way makes it work for snap package spotify？

Thanks!

**Comment by kelebek333** [comment]
>  but still no icons in top bar, even if I restart the spotify or gnome shell.

You can try add that extensions for appindicator support to Gnome Shell. https://extensions.gnome.org/extension/615/appindicator-support/   

or that for tray support => https://extensions.gnome.org/extension/1503/tray-icons/

> Then I see the ppa repo in #20 , after doing `sudo apt install spotify-tray`, it shows `Depends: spotify-client but it is not installable`, so it means only install spotify from apt repo can work.

I upload new package to PPA, spotify-client is now recommends. If recommends is enabled, you can install with following command.

`sudo apt install --no-install-recommends spotify-tray`
