### ISSUE TITLE
bug wayland plasma

### ISSUE THREAD

**Issue by userofryzen** [tsmetana/spotify-tray#23]
(spotify-tray:32252): Gdk-CRITICAL **: 18:59:34.765: gdk_x11_get_xatom_by_name_for_display: assertion 'GDK_IS_DISPLAY (display)' failed Violación de segmento (`core' generado)

using manjaro plasma wayland, i have not tested on xorg

**Comment by tsmetana** [comment]
Hello. I'm using Xfce with xorg and haven't tested on Wayland at all. I actually doubt spotify-tray would work on Wayland. However it definitely should not segfault no matter what.

**Comment by userofryzen** [comment]
why you doubt that in wayland works? :(
im using wayland since months now

**Comment by userofryzen** [comment]
but not used your app either until now

**Comment by tsmetana** [comment]
The commit a7a2968 should prevent the segfaulting on Wayland. However spotify-tray will not work there.
