### ISSUE TITLE
Support passthrough of spotify command line arguments

### ISSUE THREAD

**Issue by mrossinek** [tsmetana/spotify-tray#3]
It would be nice if the application supported passing through command line arguments to the spotify executable.
This would allow to set options like `--force-device-scale-factor` which is a setting that needs to be supplied on the command line.

**Comment by tsmetana** [comment]
Hello, this should just work: `spotify-tray -- <whatever options to pass to the spotify application>`.

**Comment by mrossinek** [comment]
Yeh I should have been able to figure this one out myself... Thanks for the hint!
