### ISSUE TITLE
Tray does not work on Debian 10.

### ISSUE THREAD

**Issue by MissingCiro** [tsmetana/spotify-tray#31]
Found the option in the settings, activated it, but when "closing" the program, it does not minimize to tray. 

Tried minimizing, but it stays in the task bar.

(I don't know if I missed a step. I did the installation steps and nothing else)

**Comment by tsmetana** [comment]
I'm sorry, but I'm confused: what settings are your referring to? There is nothing to be activated -- this is a standalone application that just wraps the official Spotify client -- it can launch it and terminate. And yes, it has limitations: if you close the main application window, it would terminate; if you minimize the main window, it would minimize just as any other window (this is somethin that I even would not attempt to change). If you want to hide the main window so only the tray icon stays, you have to left-click on the tray icon.
