### ISSUE TITLE
Add support for spotify client published by flathub

### ISSUE THREAD

**Issue by muznyo** [tsmetana/spotify-tray#33]
I have Spotify installed from Flathub, but spotify-tray does not detect it.

![image](https://user-images.githubusercontent.com/24987471/194126718-623f4dce-70d5-40a2-a54f-ed57dbe4113b.png)

Please add support for this spotify client too.

**Comment by tsmetana** [comment]
Hi. Sorry for the slow response. The error is from rpm: I don't feel like supporting the Flatpack blobs in any way. However in theory you should be able to force-install the rpm (or just install from sources to your home: `~/.local` should work for icons and desktop files) and use the `--client-path` to launch the Flatpak application. I have not tested it though.
