### ISSUE TITLE
Broken on Wayland, including via XWayland

### ISSUE THREAD

**Issue by SimPilotAdamT** [tsmetana/spotify-tray#35]
I run this package on Arch, using [this AUR PKGBUILD](https://aur.archlinux.org/packages/spotify-tray-git) with KDE Plasma as my DE, with a choice of KWin on X & Wayland, and KDE using XMonad as the WM on X.

Running Spotify using the usual `spotify` command works fine via Wayland, but trying this repo's `spotify-tray` executable does not launch Spotify, instead returning the following single line, without attempting to spawn an XWayland instance:
```bash
** (spotify-tray:154767): CRITICAL **: 01:04:24.422: No X11 display found. Quitting.
```

Any ideas?

*Edited for grammar*

**Comment by SimPilotAdamT** [comment]
I am not the only one who found this... It was reported [on the Gentoo forums](https://forums.gentoo.org/viewtopic-p-8764535.html) a few months ago.

**Comment by tsmetana** [comment]
The whole spotify-tray is built around X: I ask the window manager to find the spotify client window, I use foreing X11 window to wrap it and manipulate... So unless the X session exists (and it has to be running the spotify itself too), the whole thing can't work. I don't have DE with Wayland at hand so I guess I should document that spotify-tray is an X application and can't work on Wayland. I don't really know which interfaces are supported by XWayland. However the exact thing I'm doing (accessing other application window and manipulating it) is exactly what Wayland considers insecure and prevents from working.
