### ISSUE TITLE
Close to minimize

### ISSUE THREAD

**Issue by zt64** [tsmetana/spotify-tray#38]
Would it be possible to make it so that clicking the close button causes spotify to minimize as well?

**Comment by tsmetana** [comment]
You're not the first one suggesting this feature (see issue #8 for instance). However I'm not really sure how to implement this. I would have to hijack the termination request from the WM and after some time of tinkering I'm still not entirely sure it's possible. I may try again.

**Comment by tsmetana** [comment]
Closing. I really have no idea whether this is even doable.
