### ISSUE TITLE
make: *** No target indicated and no make file found. Stop.

### ISSUE THREAD

**Issue by hhaahhb** [tsmetana/spotify-tray#39]
in the installation when I try to put the last command "make" it says this.

**Comment by tsmetana** [comment]
Are you sure you did run `./autogen.sh` and './configure` before running make? The makefile needs to be generated first...

**Comment by hhaahhb** [comment]
> Are you sure you did run `./autogen.sh` and `./configure` before running make? The makefile needs to be generated first...

Yes, I did it in that exact order and it always gives the same thing in the make command. I don't know if I'm missing any component I should have on my PC or something, but all I know is that it doesn't work in any way.

**Comment by tsmetana** [comment]
Could you plase copy & paste the logs from those commands? They need to finish successfully in order for things to work. You might be missing something indeed.

**Comment by hhaahhb** [comment]
> Could you plase copy & paste the logs from those commands? They need to finish successfully in order for things to work. You might be missing something indeed.

Sorry for the delay, now that I saw your message. Here are:

**haah@haah-Aspire:~/spotify-tray$ ./autogen.sh**

autoreconf: export WARNINGS=
autoreconf: Entering directory '.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: configure.ac: not using Intltool
autoreconf: configure.ac: not using Gtkdoc
autoreconf: running: /usr/bin/autoconf --force
configure.ac:6: warning: The macro `AC_GNU_SOURCE' is obsolete.
configure.ac:6: You should run autoupdate.
./lib/autoconf/specific.m4:312: AC_GNU_SOURCE is expanded from...
configure.ac:6: the top level
configure.ac:10: warning: The macro `AC_HEADER_STDC' is obsolete.
configure.ac:10: You should run autoupdate.
./lib/autoconf/headers.m4:704: AC_HEADER_STDC is expanded from...
configure.ac:10: the top level
configure.ac:17: warning: AC_OUTPUT should be used without arguments.
configure.ac:17: You should run autoupdate.
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:6: installing './compile'
configure.ac:3: installing './install-sh'
configure.ac:3: installing './missing'
src/Makefile.am: installing './depcomp'
autoreconf: Leaving directory '.'

**haah@haah-Aspire:~/spotify-tray$ ./configure**

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports the include directive... yes (GNU style)
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for wchar.h... yes
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking whether _XOPEN_SOURCE should be defined... no
checking for gcc... (cached) gcc
checking whether the compiler supports GNU C... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to enable C11 features... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
./configure: line 5438: syntax error near unexpected token `GTK,'
./configure: line 5438: `PKG_CHECK_MODULES(GTK, gtk+-3.0,,)'

**haah@haah-Aspire:~/spotify-tray$ make**

make: *** No targets specified and no makefile found.  Stop.

**Comment by tsmetana** [comment]
So the configure script failed. What system do you run this on? Though I admit the `configure.ac` is in need of a cleanup, it still looks strange that autotools generate a broken configure script...

**Comment by hhaahhb** [comment]
> So the configure script failed. What system do you run this on? Though I admit the `configure.ac` is in need of a cleanup, it still looks strange that autotools generate a broken configure script... Do you have `pkgconf` installed?

I am running Ubuntu 22.04.03 LTS. I checked if pkgconf was installed and it wasn't, so I assumed it should be and installed it now.

**Comment by hhaahhb** [comment]
So, in addition to pkgconf, I ran the command "sudo apt-get install build-essential libgtk-3-dev" and then I could run the command make, it seemed to run normally... but it seems that it didn't work, even so the spotify tray icon didn't appear. Should I be using a specific version of Spotify? I am using the Flathub version.

![image](https://github.com/tsmetana/spotify-tray/assets/141190700/7016c3be-5586-4789-b62b-3c8b5e777cf1)


Here is the command log:

**haah@haah-Aspire:~/spotify-tray$ ./autogen.sh** 

autoreconf: export WARNINGS=
autoreconf: Entering directory '.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: configure.ac: not using Intltool
autoreconf: configure.ac: not using Gtkdoc
autoreconf: running: /usr/bin/autoconf --force
configure.ac:6: warning: The macro `AC_GNU_SOURCE' is obsolete.
configure.ac:6: You should run autoupdate.
./lib/autoconf/specific.m4:312: AC_GNU_SOURCE is expanded from...
configure.ac:6: the top level
configure.ac:10: warning: The macro `AC_HEADER_STDC' is obsolete.
configure.ac:10: You should run autoupdate.
./lib/autoconf/headers.m4:704: AC_HEADER_STDC is expanded from...
configure.ac:10: the top level
configure.ac:17: warning: AC_OUTPUT should be used without arguments.
configure.ac:17: You should run autoupdate.
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:6: installing './compile'
configure.ac:3: installing './install-sh'
configure.ac:3: installing './missing'
src/Makefile.am: installing './depcomp'
autoreconf: Leaving directory '.'

**haah@haah-Aspire:~/spotify-tray$ ./configure** 

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports the include directive... yes (GNU style)
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for wchar.h... yes
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking whether _XOPEN_SOURCE should be defined... no
checking for gcc... (cached) gcc
checking whether the compiler supports GNU C... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to enable C11 features... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for GTK... yes
checking for X11... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating spotify-tray.spec
config.status: creating spotify-tray.desktop
config.status: creating config.h
config.status: executing depfiles commands

**haah@haah-Aspire:~/spotify-tray$ make**

make  all-recursive
make[1]: Entering directory '/home/haah/spotify-tray'
Making all in src
make[2]: Entering directory '/home/haah/spotify-tray/src'
gcc -DHAVE_CONFIG_H -I. -I..  -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/uuid -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/x86_64-linux-gnu -I/usr/include/gio-unix-2.0 -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/at-spi-2.0 -pthread     -Wall -Wno-deprecated-declarations -g -g -O2 -MT main.o -MD -MP -MF .deps/main.Tpo -c -o main.o main.c
mv -f .deps/main.Tpo .deps/main.Po
gcc -DHAVE_CONFIG_H -I. -I..  -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/uuid -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/x86_64-linux-gnu -I/usr/include/gio-unix-2.0 -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/at-spi-2.0 -pthread     -Wall -Wno-deprecated-declarations -g -g -O2 -MT tray_status_icon.o -MD -MP -MF .deps/tray_status_icon.Tpo -c -o tray_status_icon.o tray_status_icon.c
mv -f .deps/tray_status_icon.Tpo .deps/tray_status_icon.Po
gcc -DHAVE_CONFIG_H -I. -I..  -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/uuid -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/x86_64-linux-gnu -I/usr/include/gio-unix-2.0 -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/at-spi-2.0 -pthread     -Wall -Wno-deprecated-declarations -g -g -O2 -MT proxy.o -MD -MP -MF .deps/proxy.Tpo -c -o proxy.o proxy.c
mv -f .deps/proxy.Tpo .deps/proxy.Po
gcc -DHAVE_CONFIG_H -I. -I..  -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/uuid -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/x86_64-linux-gnu -I/usr/include/gio-unix-2.0 -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/at-spi-2.0 -pthread     -Wall -Wno-deprecated-declarations -g -g -O2 -MT winctrl.o -MD -MP -MF .deps/winctrl.Tpo -c -o winctrl.o winctrl.c
mv -f .deps/winctrl.Tpo .deps/winctrl.Po
gcc -DHAVE_CONFIG_H -I. -I..  -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/uuid -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/x86_64-linux-gnu -I/usr/include/gio-unix-2.0 -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/at-spi-2.0 -pthread     -Wall -Wno-deprecated-declarations -g -g -O2 -MT tray_dbus.o -MD -MP -MF .deps/tray_dbus.Tpo -c -o tray_dbus.o tray_dbus.c
mv -f .deps/tray_dbus.Tpo .deps/tray_dbus.Po
gcc -Wall -Wno-deprecated-declarations -g -g -O2     -o spotify-tray main.o tray_status_icon.o proxy.o winctrl.o tray_dbus.o -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0  -lX11
make[2]: Leaving directory '/home/haah/spotify-tray/src'
make[2]: Entering directory '/home/haah/spotify-tray'
make[2]: Leaving directory '/home/haah/spotify-tray'
make[1]: Leaving directory '/home/haah/spotify-tray'

**Comment by tsmetana** [comment]
You need to start the spotify-tray manually: either after the spotify app itself or before it runs. Do this from the terminal window to see the potential error messages. I don't use Flatpaks, so can't verify how it behaves. It is possible the spotify tray can't find the application binary (can be set on command line) or its window (needs to have "spotify" WM class).

**Comment by hhaahhb** [comment]
> You need to start the spotify-tray manually: either after the spotify app itself or before it runs. Do this from the terminal window to see the potential error messages. I don't use Flatpaks, so can't verify how it behaves. It is possible the spotify tray can't find the application binary (can be set on command line) or its window (needs to have "spotify" WM class).

Nevermind, it worked, the tray icon is just invisible. It's there, but there's no visual icon. It doesn't bother me too much, but while I'm at it, could I add an icon?
