### ISSUE TITLE
[feature request]

### ISSUE THREAD

**Issue by userofryzen** [tsmetana/spotify-tray#4]
Request the user to vote and comment in the forum of spotify this idea:
https://community.spotify.com/t5/Live-Ideas/Desktop-Linux-Desktop-App-Minimize-to-taskbar-or-system-tray/idi-p/4804945

That is totallly relationed with the support of this package and is better because its support is inside the package and not "outside" and unnoficial

Something like:

" please, vote and comment on this topic since you are using tray icon so we can have the official support built-in the main app in the future"
and a checkbox that disable this messages each startup.

**Comment by tsmetana** [comment]
I don'l like doing this for several reasons:
1. It's annoying, I don't like other apps doing this to me
2. Spotify IIRC removed this feature on purpose; there is a change they'd consider adding it back if there was a really big pressure from users, but...
3. The "idea" you referenced has 32 votes; there's not a big chance this can change anything, moreover it asks for two things (minimize to tray or minimize to taskbar) and one of them has been already implemented
4. This is so far a simple stateless wrapper, I don't want to add any persistent data storage
