### ISSUE TITLE
Tray icon sized incorrectly

### ISSUE THREAD

**Issue by BananaManCJ** [tsmetana/spotify-tray#5]
![image](https://user-images.githubusercontent.com/47013513/84584242-94c7da00-adb6-11ea-9146-3f710c19b0e5.png)
This is the Spotify tray icon compared to Discord's tray icon. I'm on Ubuntu 20.04 with Gnome as my DE.

**Comment by tsmetana** [comment]
The Gnome extension you use to display tray icons doesn't like the size of the "spotify-client" icon or doesn't resize it properly. It's nothing I can do about. However there are other candidates for the icon file (at least on my system) so I tried to find the more suitable one from a given list. You may try the latest master and see if that helps.

**Comment by tsmetana** [comment]
Well... I'd assume it's no longer an issue. Feel free to reopen.
