### ISSUE TITLE
Start Minimised

### ISSUE THREAD

**Issue by ibrokemypie** [tsmetana/spotify-tray#7]
Is there any way to start spotify-tray minimised? That way it could be added to xinitrc to launch spotify to tray without opening a window on login. If there isn't a way, it would be a nice feature!

**Comment by tsmetana** [comment]
This is currently not possible. The problem is that the Spotify client app itself cannot be started minimized (this works only on Windows). I can hide the window as soon as it appears but it will blink for a moment.

**Comment by tsmetana** [comment]
I added a new option in the commit c7d80d0. You may try it out. It's not perfect but might be good enough.
