### ISSUE TITLE
Hiding window instead of killing the application

### ISSUE THREAD

**Issue by avemilia** [tsmetana/spotify-tray#8]
Is it possible to add a feature of hiding window instead of killing the application when the window is killed? Right now killing window kills the application, which kinda defeats the purpose of a tray icon.

**Comment by tsmetana** [comment]
So... after some hackery and testing various things I'm still unable to implement this. I'm not closing the issue -- maybe I'd get some idea.

**Comment by juxuanu** [comment]
You can just minimize it tho, it's a way to semi-implement it.

**Comment by tsmetana** [comment]
I can't even minimize it. Once the user clicks the "X" button or selects "Close window" from the WM menu the WM destroys the window. I need to break this chain of actions.

**Comment by avemilia** [comment]
I have tried `xdotool search --all --pid $(xdotool search --all --class "spotify" getwindowpid) --name "spotify free" windowminimize` but it doesn't work. I haven't tried to set some `_NET_WM_STATE`, e.g. fullscreen via `xprop -id [...] -f _NET_WM_STATE 32a -set _NET_WM_STATE _NET_WM_STATE_FULLSCREEN`, didn't work either. Perhaps GTK is playing it's part in it?

**Comment by juxuanu** [comment]
Check KDocker. It can do the trick. Maybe inspecting the source code gives you some ideas that can be work with.

**Comment by tsmetana** [comment]
No, kdocker can't do this either. If I close the application window, te application terminates too and the tray icon disappears, defintely the version 5.2 under Xfce.

**Comment by Linuxious** [comment]
Another way is when someone kills spotify is to restart it and automatically open it and hide it

**Comment by Linuxious** [comment]
The Mailspring email client has this ability maybe take a look at there source code
https://github.com/Foundry376/Mailspring

**Comment by tsmetana** [comment]
OK. I'm closing this. I have no idea how to control the protocol from outside of the application itself.
