### ISSUE TITLE
'Prev' not working

### ISSUE THREAD

**Issue by subnut** [tsmetana/spotify-tray#9]
Please help

If I select `Prev` in the context menu, it has no effect, but instead the below message is shown in the terminal running the `spotify-tray` application

```
** (spotify-tray:1006732): CRITICAL **: 15:32:42.593: D-Bus method 'Prev' call failed: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such method “Prev”
```

**Comment by tsmetana** [comment]
Silly error. Fixed.
